openapi: "3.0.2"
info:
  version: "1.0.0"
  title: TestCalculator
  description: |
    # TestCalculator - RestAPI service for execute simple math operations
basePath: /v1

paths:
  /add:
    post:
      operationId: Addition
      summary: "addition of two variables"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestArgs"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResult'
  /diff:
    post:
      operationId: Difference
      summary: "difference of two variables. arg1 - arg2"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestArgs"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResult'
  /multi:
    post:
      operationId: Multiplication
      summary: "multiplication of two variables"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestArgs"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResult'
  /div:
    operationId: Division
    summary: "Division of two variables arg1/arg2"
    requestBody:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RequestArgs"
    responses:
      "200":
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecutionResult'

components:
  schemas:
    varyDecimal:
      type: string
      pattern: '^\-?\d{1,}(\.?\d{1,6}$)?$'

    RequestArgs:
      type: object
      required:
        - arg1
        - arg2
      properties:
        arg1:
          $ref: '#/components/schemas/varyDecimal'
        arg2:
          $ref: '#/components/schemas/varyDecimal'

    ExecutionResult:
      type: object
      required:
        - result
      properties:
        result:
          type: string
